// <auto-generated />
using BlazorApp1.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp1.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230321072621_Categories")]
    partial class Categories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp1.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Books",
                            Url = "books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Movies",
                            Url = "movies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Video Games",
                            Url = "video-games"
                        });
                });

            modelBuilder.Entity("BlazorApp1.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MyPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "In May 1997, the world watched as Garry Kasparov, the greatest chess player in the world, was defeated for the first time by the IBM supercomputer Deep Blue. It was a watershed moment in the history of technology: machine intelligence had arrived at the point where it could best human intellect.\r\nIt wasn't a coincidence that Kasparov became the symbol of man's fight against the machines. Chess has long been the fulcrum in development of machine intelligence; the hoax automaton 'The Turk' in the 18th century and Alan Turing's first chess program in 1952 were two early examples of the quest for machines to think like humans -- a talent we measured by their ability to beat their creators at chess. As the pre-eminent chessmaster of the 80s and 90s, it was Kasparov's blessing and his curse to play against each generation's strongest computer champions, contributing to their development and advancing the field.",
                            ImageUrl = "https://m.media-amazon.com/images/I/41VSOxkShBL.jpg",
                            MyPrice = 9.99m,
                            Title = "Deep Thinking: Where Machine Intelligence Ends and Human Creativity Begins"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Why are some nations more prosperous than others? Why Nations Fail sets out to answer this question, with a compelling and elegantly argued new theory: that it is not down to climate, geography or culture, but because of institutions. Drawing on an extraordinary range of contemporary and historical examples, from ancient Rome through the Tudors to modern-day China, leading academics Daron Acemoglu and James A. Robinson show that to invest and prosper, people need to know that if they work hard, they can make money and actually keep it - and this means sound institutions that allow virtuous circles of innovation, expansion and peace.",
                            ImageUrl = "https://m.media-amazon.com/images/I/51n3+4Yu02L.jpg",
                            MyPrice = 7.99m,
                            Title = "Why Nations Fail: The Origins of Power, Prosperity and Poverty"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "It's the Japanese word for 'a reason to live' or 'a reason to jump out of bed in the morning'.\r\n\r\nIt's the place where your needs, desires, ambitions, and satisfaction meet. A place of balance. Small wonder that finding your ikigai is closely linked to living longer.\r\n\r\nFinding your ikigai is easier than you might think. This book will help you work out what your own ikigai really is, and equip you to change your life. You have a purpose in this world: your skills, your interests, your desires and your history have made you the perfect candidate for something. All you have to do is find it.",
                            ImageUrl = "https://m.media-amazon.com/images/I/51xwGSNX-EL.jpg",
                            MyPrice = 6.99m,
                            Title = "Ikigai: The Japanese secret to a long and happy life"
                        });
                });

            modelBuilder.Entity("BlazorApp1.Shared.Product", b =>
                {
                    b.HasOne("BlazorApp1.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
